const GET_REQUEST = "GET_REQUEST";
const GET_SUCCESS = "GET_SUCCESS";
const GET_FAIL = "GET_FAIL";
const USER_SIGNIN = "USER_SIGNIN";
const USER_SIGNOUT = "USER_SIGNOUT";
const MY_LIST = "MY_LIST";
const ADD_ITEM = "ADD_ITEM"
const REMOVE_ITEM = "REMOVE_ITEM"

export {GET_REQUEST, GET_SUCCESS, GET_FAIL, USER_SIGNIN, USER_SIGNOUT, MY_LIST, ADD_ITEM, REMOVE_ITEM}